### ISSUE TITLE
input focus is lost

### ISSUE THREAD

**Issue by Faisal49m** [jeneser/ionic2-super-bar#21]
With the setSystemUiVisibility change the input focus is lost, meaning when I have an input at the end of the screen the keyboard covers it now.

**Comment by pcsantana** [comment]
Hi @Faisal49m , how did you get it to work?

Thank you!

**Comment by pcsantana** [comment]
I figure out a workaround that can be find [here](https://github.com/jeneser/ionic-super-bar/issues/18#issuecomment-452002955)!

I hope it help someone!
Thanks
