### ISSUE TITLE
statusbar on ionic4

### ISSUE THREAD

**Issue by Calvin1121** [jeneser/ionic2-super-bar#25]
![WechatIMG24](https://user-images.githubusercontent.com/31435496/57966038-e82ee500-7976-11e9-9f91-b135e6005b38.png)
I did as you said~ and got a transparent Status Bar on Ionic4; But it seems there got another problem; the header is close to the Status Bar; and when I add style for 'ion-header' as you said, it went wrong; So, please help me to solve it~ thx~

**Comment by Calvin1121** [comment]
![image](https://user-images.githubusercontent.com/31435496/57966626-e23d0200-797e-11e9-8101-7f34eb7fbd54.png)
seems I have solved it~ anyway, thx~

**Comment by itshazlan** [comment]
how could you, apply the custom translucent? I got error on status bar padding scss.
